sudo: false

language: rust

rust:
    - nightly
    - beta
    - stable

matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
    - libxxf86vm-dev
    - libosmesa6-dev
    - libcurl4-openssl-dev      # for kcov
    - libelf-dev                # for kcov
    - libdw-dev                 # for kcov
    - cmake                     # for kcov

script:
    - cargo build -v --no-default-features --features "$FEATURES"
    - if [ "$TEST" -eq 1 ]; then cargo test -v -j 1 --no-default-features --features "$FEATURES"; fi

after_success:
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        [ "$COVERAGE" -eq 1 ] &&
        wget https://github.com/SimonKagstrom/kcov/archive/master.zip &&
        unzip master.zip && mv kcov-master kcov && mkdir kcov/build && cd kcov/build &&
        cmake .. && make && make install DESTDIR=../built && cd ../.. &&
        for file in ./target/debug/*; do ./kcov/built/usr/local/bin/kcov --verify --exclude-pattern=/.cargo,$PWD/target/debug/build,$PWD/tests ./target/kcov ${file}; done &&
        ./kcov/built/usr/local/bin/kcov --coveralls-id=${TRAVIS_JOB_ID} --merge ./target/kcov-merge ./target/kcov