sudo: required

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache:
    apt: true
    directories:
        - target/debug/deps
        - target/debug/build

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

after_success: |
    [ $TRAVIS_RUST_VERSION = stable ] &&
    cargo install cargo-kcov &&
    cargo kcov --coveralls $TRAVIS_JOB_ID