sudo: required

services:
  - docker
os:
  - linux
language: rust
rust:
  - stable
  - beta
  - nightly
cache:
  - cargo
  - apt
addons:
  apt:
    packages:
      - binutils-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

script:
- cargo build
- cargo test
- cargo bench

after_success: # - mkdir target/kcov
- docker run -it --rm --security-opt seccomp=unconfined -v $(pwd):/source ragnaroek/kcov:v33 --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/kid-*
- bash <(curl -s https://codecov.io/bash)