sudo: required

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

#cache:
#    apt: true
#    directories:
#        - target/debug/deps
#        - target/debug/build

addons:
  apt:
    packages: # all of these are for kcov.
      - cmake
      - g++
      - pkg-config
      - libcurl4-openssl-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev

after_success: |
    [ $TRAVIS_RUST_VERSION = stable ] &&
    cargo install cargo-kcov &&
    cargo kcov --print-install-kcov-sh | sh &&
    cargo kcov --coveralls $TRAVIS_JOB_ID
