dist: trusty
language: rust
sudo: required


matrix:
    include:
        - os: linux
          rust: stable

        - os: osx
          rust: stable

        - os: osx
          rust: beta

        - os: osx
          rust: nightly

cache:
  - cargo
  - apt
addons:
  apt:
    packages:
      - binutils-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

install:
    - rustc -vV
    - cargo -vV

script:
  - cargo build
  - if [[ $TRAVIS_OS_NAME = linux ]]; then cargo install cargo-kcov; cargo kcov --print-install-kcov-sh | sh; travis_wait cargo kcov --verbose --coveralls; bash <(curl -s https://codecov.io/bash); else travis_wait cargo test debug; fi
#  - cargo build --release
#  - ./target/release/kid