sudo: required

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

#cache:
#    apt: true
#    directories:
#        - target/debug/deps
#        - target/debug/build

addons:
  apt:
    packages: # all of these are for kcov.
      - cmake
      - g++
      - pkg-config
      - libcurl4-openssl-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev

# failing command: cargo kcov --print-install-kcov-sh | sh &&

after_success: |
    [ $TRAVIS_RUST_VERSION = stable ] &&
    wget https://github.com/shaneutt/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make && make install DESTDIR=../tmp && cd ../.. &&
    ls target/debug &&
    cargo install cargo-kcov &&
    cargo kcov --coveralls $TRAVIS_JOB_ID
