sudo: required

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache:
    apt: true
    directories:
        - target/debug/deps
        - target/debug/build

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

after_success: |
    [ $TRAVIS_RUST_VERSION = stable ] &&
    sudo apt-get install cmake g++ pkg-config &&
    sudo apt-get install libcurl4-openssl-dev libdw-dev binutils-dev libiberty-dev &&
    cargo install cargo-kcov &&
    cargo kcov --print-install-kcov-sh | sh &&
    cargo kcov --coveralls $TRAVIS_JOB_ID
