sudo: required

services:
  - docker
os:
  - linux
#  - osx //
language: rust
rust:
  - stable
  - beta
  - nightly
cache:
  - cargo
  - apt
addons:
  apt:
    packages:
      - binutils-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

env:
- PATH=${PATH}:${HOME}/kcov/bin

before_install: # todo: make this conditional to allow builds on osx too
- docker pull ragnaroek/kcov:v33
- docker run --security-opt seccomp=unconfined -v $(pwd):/source kcov:v33

script:
- cargo build
- cargo test
- cargo bench

after_success:
- kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/kid-*
- bash <(curl -s https://codecov.io/bash)