# from https://github.com/FractalGlobal/ntru-rs/blob/master/.travis.yml

language: rust
cache: cargo
dist: trusty
sudo: false
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

# Run builds for all the supported trains
rust:
  - stable
  - beta
  - nightly

# Load travis-cargo
before_script:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      pip install git+https://github.com/FractalGlobal/travis-cargo.git@fix-coveralls --user &&
      export PATH=$HOME/.local/bin:$PATH
      fi

# The main build
script:
  - |
      cargo build &&
      cargo test --verbose &&
      cargo bench;

# Send coverage reports and upload docs
after_success:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/kid-* &&
      fi

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""

notifications:
  email:
    recipients:
      - dominicburkart@gmail.com
    on_success: change
    on_failure: always