sudo: required

services:
  - docker
os:
  - linux
language: rust
rust:
  - stable
  - beta
  - nightly
cache:
  - cargo
  - apt
addons:
  apt:
    packages:
      - binutils-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

script:
- cargo clean
#- cargo build
- cargo test
#- cargo bench

after_success: # - mkdir target/kcov
- docker run -it --rm --security-opt seccomp=unconfined ragnaroek/kcov:v33 --coveralls-id=$TRAVIS_JOB_ID --include-pattern=kid target/kcov target/debug/*
- bash <(curl -s https://codecov.io/bash)